# permissions for end users to view uselessobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uselessobject-viewer-role
rules:
- apiGroups:
  - useless.useless.io
  resources:
  - uselessobjects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - useless.useless.io
  resources:
  - uselessobjects/status
  verbs:
  - get
